import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RootLayoutHandler from "../../utils/rootLayoutHandler";
import ContextProvider from "@/components/ContextApi/stateContext/provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SHOP.CO E-Commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
          rel="stylesheet"
        />
        <meta property="og:image" content="/images/preview-image.png" />
        <meta name="twitter:image" content="/images/preview-image.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextProvider>
          <RootLayoutHandler>{children}</RootLayoutHandler>
        </ContextProvider>

      </body>
    </html>
  );
}
